type User {
  id: ID
  username: String
  name: String
  avatar: String
  email: String
  phone: String
  language: String
  currency: String
  assets: [Asset]
  lastestTransactions: [Transaction]
}
type MapTransaction {
  key: String
  value: Transaction
}
input UserInput {
  username: String
  name: String
  avatar: String
  email: String
  phone: String
  language: String
  currency: String
  password: String
}
