type Asset {
	id: ID
	name: String
	code: String
	description: String
	unit: String
	group: ID
	amount: Int
	createdAt: String
	updatedAt: String
}

input AssetInput {
	name: String
	code: String
	description: String
	unit: String
	group: ID
	amount: Int
}