type Transaction {
	id: ID
	description: String
	amount: Int
	asset: ID
	ref: ID
	createdAt: String
	updatedAt: String
}
enum TYPE {
	CREDIT
  DEBIT
	TRANSFER
}

input TransactionInput {
	description: String
	amount: Int
	asset: ID
	type: TYPE
}

input TransactionUpdate {
	description: String
	amount: Int
	type: TYPE
}
