type Transaction {
	id: ID
	description: String
	amount: Int
	total: Int
	asset: Asset
	prev: TransactionShort
	createdAt: String
	updatedAt: String
}

input TransactionInput {
	description: String
	amount: Int
	total: Int
	user: ID
	asset: ID
	prev: ID
}

type TransactionShort {
	id: ID
	description: String
	amount: Int
	total: Int
	user: ID
	asset: ID
	prev: ID
	createdAt: String
	updatedAt: String
}